/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/cloudflyer-project/masktunnel/_bindings/python/masktunnel_go_ffi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "masktunnel_ffi.go"

#include <stdint.h>
#include <stdlib.h>

typedef struct masktunnel_buf {
    uint8_t* data;
    int64_t len;
} masktunnel_buf;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void masktunnel_free(void* p);
extern void masktunnel_buf_free(masktunnel_buf b);
extern char* masktunnel_version();
extern int64_t masktunnel_seconds();
extern char* masktunnel_parse_duration(char* s, int64_t* out);
extern char* masktunnel_wait_for_log_entries(int64_t timeout_ms, masktunnel_buf* out);
extern void masktunnel_cancel_log_waiters();
extern uint64_t masktunnel_server_create(char* opts_json);
extern char* masktunnel_server_start(uint64_t h);
extern char* masktunnel_server_start_background(uint64_t h);
extern char* masktunnel_server_stop(uint64_t h);
extern char* masktunnel_server_close(uint64_t h);
extern char* masktunnel_server_addr(uint64_t h);
extern char* masktunnel_server_reset_sessions(uint64_t h);
extern char* masktunnel_server_set_upstream_proxy(uint64_t h, char* proxy);
extern char* masktunnel_server_get_ca_pem(uint64_t h);

#ifdef __cplusplus
}
#endif
